---
jobs:
  image:
    name: Image
    secrets: inherit
    uses: MattKobayashi/actions-workflows/.github/workflows/test.yaml@686b2644a231ae70f253b9e1f63e978cddfecad5 # v1.4.1
name: Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
